
language: java
jdk:
  - openjdk8

branches:
  only: 
    - master

cache:
  directories:
    - '$HOME/.m2/'

script: "./mvnw clean package"

notifications:
  email:
    recipients:
      - gun025bba@daum.net 
